social_data_connector_facebook_connect:
    path: /admin/social-data/connector/facebook/connect
    defaults: { _controller: SocialData\Connector\Facebook\Controller\Admin\FacebookController::connectAction }

social_data_connector_facebook_connect_check:
    path: /admin/social-data/connector/facebook/check
    defaults: { _controller: SocialData\Connector\Facebook\Controller\Admin\FacebookController::checkAction }

social_data_connector_facebook_debug_token:
    path: /admin/social-data/connector/facebook/debug-token
    defaults: { _controller: SocialData\Connector\Facebook\Controller\Admin\FacebookController::debugTokenAction }

social_data_connector_facebook_feed_config:
    path: /admin/social-data/connector/facebook/feed-config
    defaults: { _controller: SocialData\Connector\Facebook\Controller\Admin\FacebookController::feedConfigAction }